phpbbgallery_index:
    pattern: /gallery
    defaults: { _controller: phpbbgallery.core.controller.index:index }
phpbbgallery_personal:
    pattern: /gallery/users
    defaults: { _controller: phpbbgallery.core.controller.index:personal }

phpbbgallery_album:
    pattern: /gallery/album/{album_id}
    defaults: { _controller: phpbbgallery.core.controller.album:base, page: 1 }
phpbbgallery_album_page:
    pattern: /gallery/album/{album_id}/page/{page}
    defaults: { _controller: phpbbgallery.core.controller.album:base }
phpbbgallery_album_upload:
    pattern: /gallery/album/{album_id}/upload
    defaults: { _controller: phpbbgallery.core.controller.album:base }

phpbbgallery_moderate_album:
    pattern: /gallery/moderate/{album_id}
    defaults: { _controller: phpbbgallery.core.controller.moderate:base }

phpbbgallery_image:
    pattern: /gallery/image/{image_id}
    defaults: { _controller: phpbbgallery.core.controller.image:base }
phpbbgallery_image_file:
    pattern: /gallery/image/{image_id}/file
    defaults: { _controller: phpbbgallery.core.controller.file:base }

phpbbgallery_search:
    pattern: /gallery/search
    defaults: { _controller: phpbbgallery.core.controller.search:base }
phpbbgallery_search_commented:
    pattern: /gallery/search/commented
    defaults: { _controller: phpbbgallery.core.controller.search:base }
phpbbgallery_search_recent:
    pattern: /gallery/search/recent
    defaults: { _controller: phpbbgallery.core.controller.search:base }
phpbbgallery_search_egosearch:
    pattern: /gallery/search/self
    defaults: { _controller: phpbbgallery.core.controller.search:base }
phpbbgallery_search_toprated:
    pattern: /gallery/search/toprated
    defaults: { _controller: phpbbgallery.core.controller.search:base }
