parameters:
    tables.phpbbgallery.permissions: %core.table_prefix%gallery_permissions
    tables.phpbbgallery.roles: %core.table_prefix%gallery_roles
    tables.phpbbgallery.users: %core.table_prefix%gallery_users

services:
    phpbbgallery.core.user:
        class: phpbbgallery\core\user
        arguments:
            - @dbal.conn
            - @dispatcher
            - %tables.phpbbgallery.users%
    phpbbgallery.core.auth:
        class: phpbbgallery\core\auth\auth
        arguments:
            - @cache
            - @dbal.conn
            - @phpbbgallery.core.user
            - %tables.phpbbgallery.permissions%
            - %tables.phpbbgallery.roles%
            - %tables.phpbbgallery.users%
    phpbbgallery.core.listener:
        class: phpbbgallery\core\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }
    phpbbgallery.core.controller.index:
        class: phpbbgallery\core\controller\index
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
